name: Build main
on:
  push:
    branches:
      - main
jobs:
  build_pr:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Clean Build
        run: ./gradlew clean build
      - name: Upload jars
        uses: actions/upload-artifact@v3
        with:
          path: build/libs/
